src/emuvim/api/heat/compute.py, src/emuvim/api/heat/heat_api_endpoint.py, src/emuvim/api/heat/heat_parser.py
Replaced all ':' with '_' in server.name to use it in docker.
Net.id is now a string.
=> Added dc_label to server.name

src/emuvim/api/heat/heat_parser.py, src/emuvim/api/heat/resources/stack.py, src/emuvim/examples/simple_heat_restapi_single_dc.py
To use them in containernet ':', '-' are not allowed in names.
=> Shorten host names

src/emuvim/api/heat/compute.py, src/emuvim/api/heat/openstack_dummies/heat_dummy_api.py, src/emuvim/api/heat/openstack_dummies/keystone_dummy_api.py, src/emuvim/api/heat/resources/stack.py
=> Keystone and heat now work with the openstack CLI clients

src/emuvim/api/heat/openstack_dummies/heat_dummy_api.py, src/emuvim/api/heat/openstack_dummies/keystone_dummy_api.py, src/emuvim/api/heat/openstack_dummies/neutron_dummy_api.py, src/emuvim/examples/simple_heat_restapi_single_dc_sandman1.py
heat_dummy_api: fix return types
keystone_dummy_api.py: fix date returned as array
neutron_dummy_api.py: add resource paths
add test file simple_heat_restapi_single_dc_sandman1.py with sandman1 ip
=> Add dummy server fixes for translator component

src/emuvim/api/heat/compute.py, src/emuvim/api/heat/openstack_dummies/heat_dummy_api.py, src/emuvim/api/heat/openstack_dummies/neutron_dummy_api.py
=> Delete functions should work now

src/emuvim/api/heat/compute.py, src/emuvim/api/heat/openstack_api_endpoint.py, src/emuvim/api/heat/openstack_dummies/neutron_dummy_api.py, src/emuvim/api/heat/resources/net.py, src/emuvim/api/heat/resources/port.py
Renamed private function (_start_compute).
Removed debug output.
Removed unused function.
Removed needless comments.
=> Listing ports with neutron after updating the stack should work again

src/emuvim/api/heat/heat_parser.py, src/emuvim/api/heat/openstack_dummies/neutron_dummy_api.py, src/emuvim/api/heat/resources/router.py, src/emuvim/api/heat/resources/server.py
Some name refactoring did not work ... updated all missing changes!
=> Fixed neutron subnet-delete call

src/emuvim/api/heat/openstack_dummies/neutron_dummy_api.py, src/emuvim/api/heat/resources/server.py
=> Neutron 'show' calls return the correct information

src/emuvim/api/heat/heat_parser.py, src/emuvim/api/heat/openstack_dummies/neutron_dummy_api.py, src/emuvim/api/heat/resources/net.py
Unused imports removed.
Outdated comments removed.
Hardcoded tenant_id is now recognizable as sutch.
Net._cidr should not be accessed directly - changed it!
=> 'Created' and 'updated at' added to subnets

src/emuvim/api/heat/compute.py, src/emuvim/api/heat/heat_parser.py, src/emuvim/api/heat/openstack_dummies/chain_dummy_api.py, src/emuvim/api/heat/resources/model.py, src/emuvim/examples/simple_heat_restapi.py, src/emuvim/test/test-template-2.yml
additionally some minor refactoring
=> Docker containers containing ENV SON_EMU_CMD work

src/emuvim/api/heat/compute.py, src/emuvim/api/heat/openstack_dummies/monitoring_dummy_api.py
Block_in and _out might not work correctly!
=> Added total network usage to the monitoring api

src/emuvim/api/heat/chain_api.py, src/emuvim/api/heat/compute.py, src/emuvim/api/heat/manage.py, src/emuvim/api/heat/openstack_dummies/neutron_dummy_api.py, src/emuvim/api/heat/openstack_dummies/nova_dummy_api.py, src/emuvim/cli/heat/__init__.py, src/emuvim/cli/heat/add_lb.sh, src/emuvim/cli/heat/manual_deploy.py, src/emuvim/dcemulator/net.py, src/emuvim/test/manual_test.sh
The call expects a format of e.g.:
{"dst_vnf_interfaces": {"dc1_man_serv1": "port-cp1-man","dc2_man_serv0": "port-cp0-man","dc2_man_serv1": "port-cp1-man"}}
with a POST call to http://localhost:4000/v1/lb/<src_vnf>/<src_vnf_interface>
at the moment it is set to ALL instead of SELECT as it makes debugging easier.
=> Loadbalancer can now be set up.

src/emuvim/api/heat/openstack_dummies/heat_dummy_api.py, src/emuvim/api/heat/openstack_dummies/keystone_dummy_api.py, src/emuvim/api/heat/openstack_dummies/neutron_dummy_api.py, src/emuvim/api/heat/openstack_dummies/nova_dummy_api.py
Further testing will be done but stack creation and updating should work at least.
=> New openstack clients should work (mostly)

misc/example-service-hot.yml, src/emuvim/examples/demo_emulator_mano_integration.py
Hi PG ... this is just a try if I can create PR's from my dev repo to your repo.
This PR includes your example template in `misc/` and my example topology in `examples`.
=> my test topo

src/emuvim/api/heat/chain_api.py, src/emuvim/api/heat/manage.py, src/emuvim/cli/heat/manual_deploy.py
this command helps monitor the current state of the emulator
=> save all set up chains and allow queries

src/emuvim/api/heat/chain_api.py, src/emuvim/api/heat/manage.py, src/emuvim/cli/heat/manual_deploy.py, src/emuvim/test/test-services/mariadb/Dockerfile, src/emuvim/test/test-services/mariadb/run.sh, src/emuvim/test/test-services/webserver/Dockerfile, src/emuvim/test/test-services/webserver/index.php, src/emuvim/test/test-services/webserver/nginx.conf, src/emuvim/test/test-services/webserver/setup.php
son emu will now be able to bootstrap vnfs by writing a file that contains chaining data.
this might be extended if need arises
=> reworked loadbalancing and dockerfiles for a demoservice

src/emuvim/api/heat/docker_util.py, src/emuvim/api/heat/heat_parser.py, src/emuvim/api/heat/openstack_dummies/heat_dummy_api.py, src/emuvim/api/heat/openstack_dummies/monitoring_dummy_api.py, src/emuvim/api/heat/openstack_dummies/nova_dummy_api.py, src/emuvim/api/heat/resources/net.py, src/emuvim/api/heat/resources/server.py
=> Subnets will now use CIDR 10.x.x.1/24 where x will be countet up

src/emuvim/api/heat/chain_api.py, src/emuvim/api/heat/manage.py, src/emuvim/api/heat/resources/net.py
reworked the add_loadbalancer calls to specify a floating loadbalancer.
actually these can be used for floating "chains" as well if you just specify one destination vnf/intf in the POST request.
=> finally a floating loadbalancer without a floating entrypoint

src/emuvim/api/heat/manage.py
now deleting chains should really delete all assigned entries
=> forgot to add cookies to the reverse flow

src/emuvim/api/heat/manage.py
ryu has some problems catching all flows for some reason
=> delete flow by cookie now uses ovs instead of ryu rest
